language: ruby

sudo: false

cache:
  bundler: true

rvm:
  - 2.4
  - 2.5
  - 2.6
  - jruby-9.1
  - jruby

matrix:
  allow_failures:

before_install:
  # Keep track of which version of node and phantomjs we're running the specs against
  - gem update --system
  - node -v
  - phantomjs -v
